language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install: make bootstrap
script: make lint test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  true:
    python: "2.7"
  distributions: sdist bdist_wheel
  password:
    secure: J3ytPZ6EzmOcx9xSXDsjyIbDnzdPkl9MwWxJnyRIOL0zxRZT2vzX8ZuOIb2YDJLaTaT2B5REaDYrr8eXYsJT9Xvv/r0SIwTukVCl0/ioH9wAShmRksOzabj/DVhzRacl1B/2bGHYaKSgeh3AxE1YxRqzEB+Wqyaw1ODklDWfCIIaTBx2NxlOzEcg92KZ7Emn8Gn+Lf/wY3NPca2yaOAz27BnenBbEYVL7ZBYDq/iOdgtmSXambwzm/hH5t71UsdWmLKktOwFcSPA87n+rNfhK6xbAS6sIrI4M54X7z85iGWCeu9Ih7xC06imLWJ/OGsmyfJXfE1fCbf86AKnoIQbc36mpWvdrnaL4GMO/MFVrWGNqEtejM5HoDef10drYycfq8wPrWGi3xGLdj4+K+/7jtFCkP/eKhOGLPnboxita0Io//p8l4Vaf4RiAqDC+rFSkwYnQx0IesXNeUCLU+1xsjT9VN2zsDnGLiCSpuQeQrg+4/Q0uFE05g+CqEWqDnJlKUswYMJ/JBjSQfv3VTa4BhjrALddK41X4lMFPpibDf5GRzoS5fNDhhOwFPfJ0iP1sIEmgVDho9n6vpY9ukOhcAmUiaTIDo63ghIXeJuTfIp2GPNgK6V+DIN/BPjS/8IPbBixgjP0rNXKfaYM5LP29y9LP1Yrq5kbI2jHGe3I+uY=
  provider: pypi
  user: twindb
